version: '3.4'

services:
  book-wishlist:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - '5000:5000'
      - '8888:8888'
      - '6380:6380'
    env_file: .env-safe
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/book-wishlist-flask
    entrypoint: /myapp/wait-for-postgres.sh
    command: /myapp/start-script.sh
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    env_file: .env-safe
    ports:
      - '5432:5432'

volumes:
  postgres: